apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pex-solution
  name: pex-solution
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pex-solution
  template:
    metadata:
      labels:
        app: pex-solution
    spec:
      containers:
        - image: trial-pex:latest
          imagePullPolicy: Never
          name: pex-solution
          resources:
            limits:
              memory: "256Mi"
              cpu: 1
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP